name: novelai_manager
description: NovelAIのプロンプトを良い感じにメモできるソフト

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  file_picker: ^5.2.5
  realm: ^0.9.0+rc
  path: ^1.8.2
  desktop_drop: ^0.4.0
  http: ^0.13.5
  url_launcher: ^6.1.7
  path_provider: ^2.0.11
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 5d45f1f # v0.11.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png

flutter_icons:
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"