name: novelai_manager
description: NovelAIのプロンプトを良い感じにメモできるソフト

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.1.1
  file_picker: ^5.2.1
  realm: ^0.5.0+beta
  path: ^1.8.2
  desktop_drop: ^0.3.3
  http: ^0.13.5
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png

flutter_icons:
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48